"""empty message

Revision ID: 500c16af6b55
Revises: 
Create Date: 2019-11-26 17:15:14.147390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500c16af6b55'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('score')
    op.drop_table('excerpt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excerpt',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='excerpt_pkey')
    )
    op.create_table('score',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('words_per_minute', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('errors', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('excerpt_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='score_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    # ### end Alembic commands ###
